name: HCL Validate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Terraform fmt 
      uses: hashicorp/terraform-github-actions/fmt@v0.3.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: .
    - name: terraform init
      uses: hashicorp/terraform-github-actions/init@v0.3.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: terraform validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: .
        AWS_REGION: us-east-1
